GET http://localhost:3000/api/profile
Content-Type: application/json
Authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzIjoxNjI2MjU5NDk3LCJpZCI6IjYwZWViODdkZGVkNWI3ZjhjM2YwMzY2MyIsInVzZXJuYW1lIjoicmFmZnkifQ.919D7CVbPJ_-_jKvXG6QY5jSo5rldwjgdQzhdls_d0k
