GET http://localhost:3000/api/profile
Content-Type: application/json
Authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzIjoxNjI2NjM1ODEyLCJpZCI6IjYwZWViODdkZGVkNWI3ZjhjM2YwMzY2MyJ9.nOqMj4WbeywTokSZBuyLC7js_tK-o-OTBob1YOvNalA
