POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "username": "raffy",
    "password": "1234"
}

###

POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "username": "raffy",
    "password": "1234",
    "email": "raffy27@pm.me"
}

###

POST http://localhost:3000/api/v1/auth/logout

###

GET http://localhost:3000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhZmZ5MjdAcG0ubWUiLCJleHAiOjE2MjY4NjE0NTcsImlkIjoiNjBlZWI4N2RkZWQ1YjdmOGMzZjAzNjYzIiwidXNlciI6InJhZmZ5In0.rJJmQXSN7QaBa2oOyl_9PR7C37M_Uzm_5axbQ6iojI0

###

GET http://localhost:3000/api/v1/users/raffy
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhZmZ5MjdAcG0ubWUiLCJleHAiOjE2MjY4NjE0NTcsImlkIjoiNjBlZWI4N2RkZWQ1YjdmOGMzZjAzNjYzIiwidXNlciI6InJhZmZ5In0.rJJmQXSN7QaBa2oOyl_9PR7C37M_Uzm_5axbQ6iojI0